<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="The-Beast" failures="3" tests="14" name="FunctionalTests" time="417.686" errors="0" timestamp="2023-11-19T16:08:42 IST">
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithEmptyCredTest" time="0.382"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.389"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.386"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.386"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.511"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordCheckTest" time="0.37"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordCheckTest" time="0.372"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordTest" time="0.38"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordTest" time="0.352"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="15.639">
    <failure type="java.lang.AssertionError" message="Going to next step of signUp after entering invalid Mobile number. expected [Please enter a valid mobile phone number with area code.] but found [Amazon Phone Verification]">
      <![CDATA[java.lang.AssertionError: Going to next step of signUp after entering invalid Mobile number. expected [Please enter a valid mobile phone number with area code.] but found [Amazon Phone Verification]
at com.testing.amazon.tests.functional.SignUpTest.signUpWithInvalidPhoneNumberTest(SignUpTest.java:132)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInvalidPhoneNumberTest -->
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="159.231"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="14.688"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidUserNameTest" time="18.827">
    <failure type="java.lang.AssertionError" message="Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]">
      <![CDATA[java.lang.AssertionError: Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]
at com.testing.amazon.tests.functional.SignUpTest.signUpWithInvalidUserNameTest(SignUpTest.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInvalidUserNameTest -->
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidUserNameTest" time="32.894">
    <failure type="java.lang.AssertionError" message="Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]">
      <![CDATA[java.lang.AssertionError: Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]
at com.testing.amazon.tests.functional.SignUpTest.signUpWithInvalidUserNameTest(SignUpTest.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInvalidUserNameTest -->
</testsuite> <!-- FunctionalTests -->
