<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="The-Beast" failures="2" tests="14" name="FunctionalTests" time="380.014" errors="0" timestamp="2023-11-20T13:32:45 IST">
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithEmptyCredTest" time="0.517"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.495"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.701"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.897"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidEmailTest" time="0.474"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordCheckTest" time="0.695"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordCheckTest" time="0.421"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordTest" time="0.384"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPasswordTest" time="0.496"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="15.884">
    <failure type="java.lang.AssertionError" message="Going to next step of signUp after entering invalid Mobile number. expected [Please enter a valid mobile phone number with area code.] but found [Amazon Phone Verification]">
      <![CDATA[java.lang.AssertionError: Going to next step of signUp after entering invalid Mobile number. expected [Please enter a valid mobile phone number with area code.] but found [Amazon Phone Verification]
at com.testing.amazon.tests.functional.SignUpTest.signUpWithInvalidPhoneNumberTest(SignUpTest.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInvalidPhoneNumberTest -->
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="25.018"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidPhoneNumberTest" time="89.901"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidUserNameTest" time="1.285"/>
  <testcase classname="com.testing.amazon.tests.functional.SignUpTest" name="signUpWithInvalidUserNameTest" time="20.063">
    <failure type="java.lang.AssertionError" message="Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]">
      <![CDATA[java.lang.AssertionError: Going to next step of signUp after entering invalid user name. did not expect [Amazon Phone Verification] but found [Amazon Phone Verification]
at com.testing.amazon.tests.functional.SignUpTest.signUpWithInvalidUserNameTest(SignUpTest.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- signUpWithInvalidUserNameTest -->
</testsuite> <!-- FunctionalTests -->
